name: mainNew

on: 
  push:
    branches:
      - master
      - main
    paths:
      - '**ockerfile'




jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
